### PR TITLE
fixes #1

### LINKED ISSUE #1: Nix segfaults on installation
See https://github.com/NixOS/nix/issues/2733

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -11,6 +11,10 @@ async function run() {
     const PATH = process.env.PATH;  
     const CERTS_PATH = home + '/.nix-profile/etc/ssl/certs/ca-bundle.crt';
 
+    // Workaround a segfault: https://github.com/NixOS/nix/issues/2733
+    await exec.exec("sudo", ["mkdir", "-p", "/etc/nix"]);
+    await exec.exec("sudo", ["echo", "http2 = false", ">>", "/etc/nix/nix.conf"]);
```
Comment (roberth) [inline src/main.ts]: :100: why this project is useful!
